[package]
name = "rusty_git"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.15", features = ["derive"]}
flate2 = "1.0.31"
hex = "0.4.3"
sha1 = "0.10.6"
sha2 = "0.10.8"
